TrainingModule/Controllers/FilehelperController.cs
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Hosting;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using TrainingModule.Data;
using TrainingModule.Models;

namespace TrainingModule.Controllers
{
    public class FileHelperController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IWebHostEnvironment _hostingEnvironment = null;

        public FileHelperController(ApplicationDbContext context, IWebHostEnvironment hostingEnvironment)
        {
            _context = context;
            _hostingEnvironment = hostingEnvironment;
        }

        [HttpGet]
        public IActionResult Index(string fileName = "")
        {
            FileHelper fileObj = new FileHelper();
            fileObj.Name = fileName;
            string path = $"{_hostingEnvironment.WebRootPath}\\files\\";
            int nId = 1;
            foreach (string pdfPath in Directory.EnumerateFiles(path, "*.pdf"))
            {
                fileObj.Files.Add(new FileHelper()
                {
                    FileId = nId++,
                    Name = Path.GetFileName(pdfPath),
                    Path = pdfPath
                });
            }
            return View(fileObj);
        }


        [HttpPost]
        public IActionResult Index(IFormFile file, [FromServices] IWebHostEnvironment hostingEnvironment )
        {
            string fileName = $"{hostingEnvironment.WebRootPath}\\files\\{ file.FileName}";
            using (FileStream fileStream = System.IO.File.Create(fileName))
            {
                file.CopyTo(fileStream);
                fileStream.Flush();
                fileStream.Close();
            }
            return Index();
        }
        public IActionResult PDFViewerNewTab(string fileName)
        {
            string path = _hostingEnvironment.WebRootPath + "\\files\\" + fileName;
            return File(System.IO.File.ReadAllBytes(path), "application/pdf");
        }
    }
}

TrainingModule/Views/FileHelper/Index.cshtml
@model FileHelper
@{
    ViewData["Title"] = "Index";
} 

<form asp-controller="FileHelper" asp-action="Index" method="post" enctype="multipart/form-data">
    <input type="file" name="file"/>
    <hr />
    <button type="submit">Upload</button>

</form>
@if (Model !=null)
 {
    <hr />
    <table class="table table-bordered table-striped" cellpadding="0" cellspacing="0" border="1">
        <thead>

            <tr>
                <th>Number</th>
                <th>PDF Name</th>
                <th>Display Type</th>

            </tr>
        </thead>
        <tbody>
            @foreach(FileHelper file in Model.Files)
                {
            <tr>
                <td>@file.FileId</td>
                <td>@file.Name</td>
                <td>
                    <a href="../FileHelper/Index?fileName=@file.Name" style="margin-right:10px">Current Page</a>
                    <a href="../FileHelper/PDFViewerNewTab?fileName=@file.Name" target="_blank">New Tab</a>
                </td>
            </tr>
                }
        </tbody>
    </table>
 }
<br /><br />
<embed id="embPDF"src="/files/@Model.Name" style="width:100%; height:1200px;" />