TrainingModule/Controllers/HomeController.cs
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging;
using Newtonsoft.Json.Linq;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using TrainingModule.ActionFilters;

using TrainingModule.Data;

using TrainingModule.Models;

using TrainingModule.ViewModel;


namespace TrainingModule.Controllers
{

    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
      

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
           
        }
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult YoutubeIndex()
        {
            WebRequest request = WebRequest.Create("https://youtube.googleapis.com/youtube/v3/search?part=snippet&maxResults=50&q=hematology&key=" + YoutubeApiKeys.apiKey);
            WebResponse response = request.GetResponse();
            Stream stream = response.GetResponseStream();
            StreamReader reader = new StreamReader(stream);
            string responseFromServer = reader.ReadToEnd();
            JObject parsedString = JObject.Parse(responseFromServer);
            Youtube search = parsedString.ToObject<Youtube>();
            return View(search);

        }
        //[HttpPost]
        //public async Task<IActionResult> Comment(CommentViewModel vm)
        //{
        //    if (!ModelState.IsValid)
        //        return RedirectToAction("Post", new { id = vm.PostId });

        //    var post = _repo.GetPost(vm.PostId);
        //    if (vm.MainCommentId == 0)
        //    {
        //        post.MainComments = post.MainComments ?? new List<MainComment>();

        //        post.MainComments.Add(new MainComment
        //        {
        //            Message = vm.Message,
        //            Created = DateTime.Now,
        //        });

        //        _repo.UpdatePost(post);
        //    }
        //    else
        //    {
        //        var comment = new SubComment
        //        {
        //            MainCommentId = vm.MainCommentId,
        //            Message = vm.Message,
        //            Created = DateTime.Now,
        //        };
        //        _repo.AddSubComment(comment);
        //    }

        //    await _repo.SaveChangesAsync();

        //    return RedirectToAction("Post", new { id = vm.PostId });
        //}
        //public IActionResult Privacy()
        //{
        //    return View();
        //}


    }
}

TrainingModule/Controllers/UpdatesController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using TrainingModule.Data;
using TrainingModule.Models;

namespace TrainingModule.Controllers
{
    [Authorize(Roles = "Manager")]
    public class UpdatesController : Controller
    {
        private ApplicationDbContext _context;
        public UpdatesController(ApplicationDbContext context)
        {
            _context = context;
        }
        [AllowAnonymous]
        public IActionResult Index()
        {
            List<Update> update = _context.Updates.ToList();

            return View(update);
        }
        public IActionResult Create()
        {
            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult EditNewsletter(Update update)
        {
            if (ModelState.IsValid)
            {
                if (update.UpdateId == 0)
                {
                    _context.Updates.Add(update);
                }
                else
                {
                    _context.Updates.Update(update);
                }
                _context.SaveChanges();
                return RedirectToAction(nameof(Index));
            }

            return View(update);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Update update)
        {
            try
            {
                _context.Updates.Add(update);
                _context.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            catch (Exception e)
            {
                Console.WriteLine(e);
                return View();
            }
        }
        public ActionResult Edit(int id)
        {
            var update = _context.Updates.Where(e => e.UpdateId == id).FirstOrDefault();
            return View(update);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(int id, Update update)
        {
            try
            {
                _context.Updates.Update(update);
                _context.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                Console.WriteLine("Error");
                return View();
            }

        }
        public IActionResult Delete(int id)
        {
            var data = _context.Updates.FirstOrDefault(o => o.UpdateId == id);
            _context.Updates.Remove(data);
            _context.SaveChanges();
            return RedirectToAction(nameof(Index));
        }

    }
}

TrainingModule/Views/Home/Index.cshtml
@*@using Microsoft.Extensions.Options*@ 
@model TrainingModule.Models.Youtube
@{
    ViewData["Title"] = "Home Page";
}


<!DOCTYPE html>
<html lang="en">
<head>
    <title>Bootstrap Example</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    <style>
        img {
            border: 2px solid #ddd; /* Gray border */
            border-radius: 5px; /* Rounded border */
            padding: 3px; /* Some padding */
            width: 250px;
            height: 200px
        }

        .row {
            display: flex;
        }

        /* Create three equal columns that sits next to each other */
        .column {
            flex: 25%;
            padding: 10px;
        }
        h1 {
            font-weight: bold;
        }
    </style>
</head>
<body>
    <div class="text-center">
        <h1>Welcome to Team Boards!</h1>
    </div>
    <div class="carousel-inner">
        <div class="carousel-item active">

            <img src="Images/multicare.png" class="d-block w-100" alt="multicare">
        </div>
    </div>
    <br />
    @*need to fix the routing issue for the picture link*@
<p>
    <strong>Our Mission: </strong>Partnering for healing and a healthy future<br>
    <strong>Our Vision: </strong>MultiCare will be the Pacific Northwest's hightest value system of health<br>
    <strong>Our Values: </strong>Respect / Integrity / Stewardship / Excellence / Collaboration / Kindness
</p>
    <div class="row"> 
        <div class="column">
            <a href="@Url.Action("Index", "Updates")">
                <img src="Images/newsletter.png" alt="newsletter" style="width:100%">
                <div class="text-block">
                    <h4>Team Updates/Newsletter</h4>
                </div>
            </a>
</div>
        <div class="column">
            <a href="@Url.Action("Index", "Trainings")">
                <img src="Images/training.png" alt="training" style="width:100%">
                <div class="text-block">
                    <h4>Training Materials/Comments</h4>
                </div>
            </a>
</div>
        <div class="column">
            <a href="@Url.Action("Index", "Suggestions")">
                <img src="Images/feedback.png" alt="feedback" style="width:100%">
                <div class="text-block">
                    <h4>Suggestion Box</h4>
                </div>
            </a>
        </div>
    </div>

</body>
</html>

TrainingModule/Views/Home/YoutubeIndex.cshtml
@model TrainingModule.Models.Youtube
@{
    ViewData["Title"] = "YoutubeIndex";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<p>Youtube Api</p>
@foreach (var item in Model.items)
{
    <img src="@item.snippet.thumbnails.medium.url" />
    <p><a href="https://www.youtube.com/watch/@item.id.videoId">@item.snippet.title"</a></p>

}